spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sqltest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "052011"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.springbootdemo.vo,org.example.springbootdemo.dto,org.example.springbootdemo.pojo,org.example.springbootdemo.query,org.example.springbootdemo.entity
  global-config:
    db-config:
      id-type: assign_id   # 雪花算法主键策略
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
